title: SUPER KUVAR ğŸ³
logo: /assets/img/logo.png
description: Tradicioalna srpska kuhinja i praktiÄni recepti iz bakinih vitrina.
paginate: 12
google_analytics: UA-42249092-1
theme: jekyll-theme-dinky

gems:
- jekyll-seo-tag



