title: SUPER KUVAR ğŸ³
logo: /assets/img/logo.png
description: Tradicioalna kuhinja i praktiÄni recepti iz bakinih vitrina.
google_analytics: UA-42249092-1
redirects: yes
plugins:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed



